apiVersion: v1
kind: Service
metadata:
  name: benchmarking-service
  namespace: rossoctl-system
  labels:
    app: benchmarking-service
spec:
  type: ClusterIP
  selector:
    app: benchmarking-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
